-- JOIN 없어진 기록찾기

-- 풀이 1 - 서브쿼리
--SELECT ANIMAL_ID, NAME
--FROM ANIMAL_OUTS
--WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_INS)
--ORDER BY ANIMAL_ID;

-- 풀이 2 - left join
SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS A
LEFT JOIN ANIMAL_INS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID IS NULL
ORDER BY A.ANIMAL_ID;