-- [JOIN] 오랜 기간 보호한 동물(1)

-- left join + 서브쿼리
-- SELECT NAME, DATETIME
-- FROM (SELECT A.NAME, A.DATETIME
--       FROM ANIMAL_INS A, ANIMAL_OUTS B
--       WHERE A.ANIMAL_ID = B.ANIMAL_ID(+)
--       AND B.ANIMAL_ID IS NULL
--       ORDER BY A.DATETIME)
-- WHERE ROWNUM < 4;

-- fetch
SELECT A.NAME, A.DATETIME
FROM ANIMAL_INS A, ANIMAL_OUTS B
WHERE A.ANIMAL_ID = B.ANIMAL_ID(+)
AND B.ANIMAL_ID IS NULL
ORDER BY A.DATETIME
fetch first 3 rows only;